[package]
name = "uefi"
version = "0.1.0"
authors = ["Gabriel Majeri <gabriel.majeri6@gmail.com>"]
readme = "README.md"
publish = false
edition = "2018"

[dependencies]
bitflags = "1"
log = { version = "0.4", default-features = false }
ucs2 = "0.1"
uefi-derive = { path = "uefi-derive" }

[workspace]
members = [
    "uefi-alloc",
    "uefi-derive",
    "uefi-exts",
    "uefi-logger",
    "uefi-services",
    "uefi-test-runner",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"